import { Conversation, Agent } from './types';

export const agents: Agent[] = [
  { id: 'a1', name: 'Noa Cohen', status: 'online', activeTickets: 4 },
  { id: 'a2', name: 'Yael Levi', status: 'online', activeTickets: 3 },
  { id: 'a3', name: 'Amit Ben-David', status: 'away', activeTickets: 2 },
];

export const conversations: Conversation[] = [
  {
    id: 'c1',
    customer: {
      id: 'u1',
      name: 'Sarah Mitchell',
      email: 'sarah.m@gmail.com',
      channels: ['email', 'instagram'],
      tags: ['vip', 'returning'],
    },
    channel: 'email',
    status: 'open',
    priority: 'high',
    subject: 'Order not received - #FR-20487',
    lastMessage: "Hi, I placed an order 10 days ago and still haven't received it. Can you help?",
    lastMessageTime: new Date('2026-04-05T09:23:00'),
    assignedTo: 'a1',
    unread: true,
    tags: ['shipping', 'urgent'],
    messages: [
      {
        id: 'm1',
        conversationId: 'c1',
        sender: 'customer',
        senderName: 'Sarah Mitchell',
        content: "Hi there! I placed an order for frelo Dark Chocolate balls about 10 days ago (order #FR-20487) and still haven't received it. The tracking hasn't updated in 5 days. Can you please look into this?",
        timestamp: new Date('2026-04-05T09:23:00'),
        channel: 'email',
      },
    ],
  },
  {
    id: 'c2',
    customer: {
      id: 'u2',
      name: 'Mike Johnson',
      email: 'mike.j@outlook.com',
      channels: ['instagram'],
      tags: ['new'],
    },
    channel: 'instagram',
    status: 'open',
    priority: 'medium',
    subject: 'DM: Product question',
    lastMessage: 'Hey! Is frelo actually vegan? What about the chocolate coating?',
    lastMessageTime: new Date('2026-04-05T08:45:00'),
    assignedTo: 'a1',
    unread: true,
    tags: ['product-info'],
    messages: [
      {
        id: 'm2',
        conversationId: 'c2',
        sender: 'customer',
        senderName: 'Mike Johnson',
        content: "Hey! Is frelo actually vegan? What about the chocolate coating? I've been burned by brands saying they're plant-based but using milk derivatives.",
        timestamp: new Date('2026-04-05T08:45:00'),
        channel: 'instagram',
      },
    ],
  },
  {
    id: 'c3',
    customer: {
      id: 'u3',
      name: 'Linda Park',
      email: 'linda.park@yahoo.com',
      channels: ['facebook'],
      tags: ['returning'],
    },
    channel: 'facebook',
    status: 'pending',
    priority: 'medium',
    subject: 'Subscription question',
    lastMessage: 'Can I change my subscription from monthly to bi-weekly?',
    lastMessageTime: new Date('2026-04-04T22:10:00'),
    assignedTo: 'a2',
    unread: false,
    tags: ['subscription'],
    messages: [
      {
        id: 'm3a',
        conversationId: 'c3',
        sender: 'customer',
        senderName: 'Linda Park',
        content: "I currently have a monthly subscription but I run out before my next delivery. Can I switch to bi-weekly?",
        timestamp: new Date('2026-04-04T18:30:00'),
        channel: 'facebook',
      },
      {
        id: 'm3b',
        conversationId: 'c3',
        sender: 'agent',
        senderName: 'Yael Levi',
        content: "Hi Linda! Great to hear you're loving frelo so much that you need more! Let me check what subscription options we have available for you.",
        timestamp: new Date('2026-04-04T19:15:00'),
        channel: 'facebook',
      },
      {
        id: 'm3c',
        conversationId: 'c3',
        sender: 'customer',
        senderName: 'Linda Park',
        content: "Thank you! Yes, I take one every morning as part of my routine and my husband started stealing them too haha. So one pouch a month isn't cutting it anymore.",
        timestamp: new Date('2026-04-04T22:10:00'),
        channel: 'facebook',
      },
    ],
  },
  {
    id: 'c4',
    customer: {
      id: 'u4',
      name: 'James Rivera',
      email: 'jrivera@gmail.com',
      channels: ['tiktok'],
      tags: ['influencer'],
    },
    channel: 'tiktok',
    status: 'open',
    priority: 'high',
    subject: 'Comment: Collab inquiry',
    lastMessage: "Love this product! I'm a fitness creator with 250K followers. Let's collab?",
    lastMessageTime: new Date('2026-04-05T07:30:00'),
    assignedTo: 'a2',
    unread: true,
    tags: ['influencer', 'partnership'],
    messages: [
      {
        id: 'm4',
        conversationId: 'c4',
        sender: 'customer',
        senderName: 'James Rivera',
        content: "Love this product! I've been taking creatine for years but the powder is so annoying. I'm a fitness and wellness creator with 250K followers on TikTok. Would love to do a collab/review. DM me!",
        timestamp: new Date('2026-04-05T07:30:00'),
        channel: 'tiktok',
      },
    ],
  },
  {
    id: 'c5',
    customer: {
      id: 'u5',
      name: 'Emma Watson',
      email: 'emma.w@proton.me',
      channels: ['whatsapp'],
      tags: ['returning'],
    },
    channel: 'whatsapp',
    status: 'open',
    priority: 'low',
    subject: 'Re-order question',
    lastMessage: 'What flavors do you have available right now?',
    lastMessageTime: new Date('2026-04-05T06:15:00'),
    assignedTo: 'a3',
    unread: false,
    tags: ['product-info'],
    messages: [
      {
        id: 'm5a',
        conversationId: 'c5',
        sender: 'customer',
        senderName: 'Emma Watson',
        content: "Hi! I tried frelo at a friend's house and I'm hooked. What flavors do you have available right now? And do you ship to the UK?",
        timestamp: new Date('2026-04-05T06:15:00'),
        channel: 'whatsapp',
      },
    ],
  },
  {
    id: 'c6',
    customer: {
      id: 'u6',
      name: 'David Kim',
      email: 'dkim@gmail.com',
      channels: ['email'],
      tags: ['returning', 'vip'],
    },
    channel: 'email',
    status: 'resolved',
    priority: 'low',
    subject: 'Thank you for the amazing product!',
    lastMessage: "You're welcome David! We're so glad you're enjoying frelo.",
    lastMessageTime: new Date('2026-04-04T15:00:00'),
    assignedTo: 'a1',
    unread: false,
    tags: ['feedback', 'positive'],
    messages: [
      {
        id: 'm6a',
        conversationId: 'c6',
        sender: 'customer',
        senderName: 'David Kim',
        content: "Just wanted to say — I've been taking frelo for 3 months now and the difference in my energy and focus is incredible. As someone who's 62 and vegan, I was really struggling with finding a creatine I'd actually take every day. This is it. Thank you!",
        timestamp: new Date('2026-04-04T14:20:00'),
        channel: 'email',
      },
      {
        id: 'm6b',
        conversationId: 'c6',
        sender: 'agent',
        senderName: 'Noa Cohen',
        content: "David, this truly made our day! We're so glad frelo has become part of your daily ritual. Your story is exactly why we created this — real food, real results, and something you actually look forward to. Thank you for sharing, and here's to many more months of feeling great!",
        timestamp: new Date('2026-04-04T15:00:00'),
        channel: 'email',
      },
    ],
  },
  {
    id: 'c7',
    customer: {
      id: 'u7',
      name: 'Rachel Green',
      email: 'rachel.g@icloud.com',
      channels: ['instagram', 'email'],
      tags: ['new'],
    },
    channel: 'instagram',
    status: 'open',
    priority: 'urgent',
    subject: 'Allergic reaction concern',
    lastMessage: 'Does frelo contain any nuts? I have a severe tree nut allergy.',
    lastMessageTime: new Date('2026-04-05T10:05:00'),
    assignedTo: 'a1',
    unread: true,
    tags: ['allergen', 'urgent', 'health'],
    messages: [
      {
        id: 'm7',
        conversationId: 'c7',
        sender: 'customer',
        senderName: 'Rachel Green',
        content: "Hi! Before I order — does frelo contain any tree nuts or is it processed in a facility that handles nuts? I have a severe tree nut allergy and need to be really careful. The ingredients list on your site says coconut oil but I know coconut isn't technically a tree nut. Any other allergens I should know about?",
        timestamp: new Date('2026-04-05T10:05:00'),
        channel: 'instagram',
      },
    ],
  },
];
